[package]
name = "deno_usb"
version = "0.0.1"
authors = ["Brandon Ros <brandonros1@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.8"
deno_core = "0.69.0"
rusb = "0.5"
